# version format
version: 0.0.{build}

# cache the "downloads" folder in the build folder
# refresh cache, if appveyor.yml changes
cache:
  - downloads -> appveyor.yml

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input

before_build: 
  # download
  - build-scripts\1-download.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\downloads"
  # extract
  - build-scripts\2-extract.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\extracted"
  # copy
  - build-scripts\3-copy.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\repackage"
  
build_script:
  - build-tools\innosetup\iscc /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\fife-sdk.iss

after_build:
  - dir C:\projects\_build /s
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\_build\FifeSDK-%APPVEYOR_BUILD_VERSION%-Setup-VC14-x86.exe"

